markdown: kramdown
permalink: /:title/
url: https://iami.xyz
highlighter: rouge
name: I的手札
description: I | Life is Short, But Art is Long.
author: I
email: mour@iami.xyz
weibo: 
hub: mylamour
safe: true
paginate: 33
about: "Never Stop。"
gems :
  - jekyll-paginate
